### ISSUE TITLE
Config files pushed by chart should be optional (to allow decision on using the ones in the container)

### ISSUE THREAD

**Issue by pcm32** [CloudVE/galaxy-helm#49]
I tried using the setup with a container that extends galaxy/galaxy:19.05 with all the config files that I use in my previous setup (as it also contains whitelists, dynamic destinations, etc), but even if I don't set `configs.<some-config> = file-content`, these files get mounted from the config files, overriding the ones I want to use.

I used the following helm config file with the chart:

```
image:
  repository: pcm32/galaxy-helm-v3
  tag: 19.05
  pullPolicy: IfNotPresent

configs:
  galaxy.yml: |
    uwsgi:
      virtualenv: /galaxy/server/.venv
      processes: 1
      http: 0.0.0.0:8080
      static-map: /static/style=/galaxy/server/static/style/blue
      static-map: /static=/galaxy/server/static
      static-map: /favicon.ico=/galaxy/server/static/favicon.ico
      pythonpath: /galaxy/server/lib
      thunder-lock: true
      manage-script-name: true
      mount: {{.Values.ingress.path}}=galaxy.webapps.galaxy.buildapp:uwsgi_app()
      buffer-size: 16384
      offload-threads: 2
      threads: 4
      die-on-term: true
      master: true
      hook-master-start: unix_signal:2 gracefully_kill_them_all
      enable-threads: true
      py-call-osafterfork: true
    galaxy:
      database_connection: 'postgresql://{{.Values.postgresql.galaxyDatabaseUser}}:{{.Values.postgresql.galaxyDatabasePassword}}@{{ template "galaxy-postgresql.fullname" . }}/galaxy'
      integrated_tool_panel_config: "/galaxy/server/config/mutable/integrated_tool_panel.xml"
      containers_resolvers_config_file: "/galaxy/server/config/container_resolvers_conf.xml"
      job_config_file: "/galaxy/server/config/job_conf.xml"
      brand: "scRNA-Seq Tertiary A."
      admin_users: admin@email.co.uk
      allow_user_creation: true
      allow_user_deletion: true
      cleanup_job: always
      enable_beta_mulled_containers: true
      conda_auto_install: false

extraEnv:
  - name: GALAXY_DB_USER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ .Release.Name }}-galaxy-db-password"
        key: galaxy-db-password
  - name: GALAXY_RUNNERS_K8S_PERSISTENT_VOLUME_CLAIMS
    value: '{{ template "galaxy.pvcname" . }}:{{.Values.persistence.mountPath}}'
  - name: GALAXY_RUNNERS_K8S_NAMESPACE
    value: "{{ .Release.Namespace }}"
  - name: GALAXY_RUNNERS_K8S_RUN_AS_USER_ID
    value: "101"
  - name: GALAXY_RUNNERS_K8S_RUN_AS_GROUP_ID
    value: "101"
  - name: GALAXY_RUNNERS_K8S_SUPPLEMENTAL_GROUP_ID
    value: "101"
  - name: GALAXY_RUNNERS_K8S_FS_GROUP_ID
    value: "101"
  - name: GALAXY_DESTINATIONS_DOCKER_DEFAULT
    value: k8s_default
  - name: GALAXY_DESTINATIONS_NO_DOCKER_DEFAULT
    value: local_no_container
  - name: GALAXY_DESTINATIONS_DEFAULT
    value: dynamic-k8s-dispatcher
  - name: GALAXY_RUNNERS_ENABLE_LOCAL
    value: "true"
  - name: GALAXY_RUNNERS_ENABLE_K8S
    value: "true"
```

doing:

```
cd galaxy-kuberntes/galaxy
helm install -f <file-above>.yaml .
```

Then, inside the running container on k8s, I see the file injected by the chart for `job_conf.xml` instead of what I loaded into the container specified.
